# @package _global_

model:
  resnet_name: "resnet50"
  pretrained: false
  
  lr: 0.0005          # Base learning rate (will be scaled)
  weight_decay: 0.05
  warmup_epochs: 10
  min_lr: 0.0         
