# @package _global_

model:
  vit_model_name: "vit_base_patch16_224"
  pretrained: false
  ibot_separate_head: false
  drop_path_rate: 0.1
  
  lr: 0.001           # Base learning rate (will be scaled by batch size & world size)
  weight_decay: 0.04
  warmup_epochs: 10
  min_lr: 0.00001    